"""Prompt templates shared by avatar and flight asset generators."""

STYLE_CORE = (
    "CRITICAL STYLE REQUIREMENTS — you MUST follow every single one:\n"
    "1. PIXEL ART: Use the EXACT same pixel art style as the reference sprite. Copy its pixel density, "
    "thick dark outlines (2-3px), chunky proportions, warm retro color palette, and cel-shading technique.\n"
    "2. CONSISTENCY: The output must look like it was drawn by the same artist as the reference. "
    "Match outline thickness, level of pixelation, color saturation, and shading direction.\n"
    "3. TRANSPARENT BACKGROUND: The background MUST be fully transparent (alpha = 0). "
    "Do NOT draw any ground, shadow, floor, scenery, gradient, or solid background color.\n"
    "4. SINGLE SUBJECT: The dog character must be the ONLY element in the image.\n"
    "5. OUTPUT: PNG with transparency. No text, no labels, no watermarks.\n"
    "6. PROPORTIONS: Short stubby legs, stocky chunky body, large expressive head — "
    "exactly like the reference sprite proportions. NOT realistic proportions."
)

PROFILE_PROMPT = (
    "I am providing TWO images:\n"
    "IMAGE 1 (first): A photo of a real dog — this is the dog you must draw.\n"
    "IMAGE 2 (second): A reference pixel art PROFILE from my game — you MUST match this EXACT art style, "
    "proportions, and level of detail.\n\n"
    "Generate a 350x350 pixel art PORTRAIT of the dog from IMAGE 1.\n"
    "- Sitting pose, facing slightly toward the viewer (3/4 front view)\n"
    "- Happy expression with visible tongue\n"
    "- Dog centered and filling ~90% of the square canvas\n"
    "- Character select portrait for a retro arcade game\n"
    "- Study IMAGE 2 carefully: match the exact same outline thickness, pixel density, "
    "color palette warmth, shading style, and chunky proportions\n\n"
    "{style_core}\n"
    "Output exactly ONE square image, 350x350 pixels."
)

RUN_SPRITE_PROMPT = (
    "I am providing THREE images:\n"
    "IMAGE 1 (first): A photo of a real dog — this is the dog you must draw.\n"
    "IMAGE 2 (second): The pixel art profile I already generated for this dog — "
    "you MUST draw the EXACT SAME character with identical colors, markings, and proportions.\n"
    "IMAGE 3 (third): A reference RUN SPRITE SHEET from my game — you MUST match this EXACT layout, "
    "frame size, art style, and dog proportions.\n\n"

    "Generate a HORIZONTAL SPRITE SHEET: exactly 1500x500 pixels total, containing EXACTLY 3 frames "
    "of 500x500 pixels each, placed left to right with NO gaps.\n"
    "Each frame shows the dog in SIDE VIEW facing RIGHT in a run cycle:\n"
    "- Frame 1 (left 500px): Standing/ready stance, legs neutral\n"
    "- Frame 2 (center 500px): Mid-stride, legs extended, body bouncing up slightly\n"
    "- Frame 3 (right 500px): Opposite leg positions from frame 1\n\n"
    "CRITICAL RULES:\n"
    "- The dog must be the SAME SIZE in all 3 frames (same body height and width)\n"
    "- The dog must be CENTERED vertically in each 500x500 frame\n"
    "- Only the legs change between frames — body/head stay consistent\n"
    "- Match IMAGE 3's layout EXACTLY: same frame spacing, same dog size relative to frame\n"
    "- The dog MUST look identical to IMAGE 2 (same pixel art character)\n\n"
    "{style_core}\n"
    "Output exactly ONE wide image: 1500x500 pixels with all 3 frames side by side."
)

EAT_SPRITE_PROMPT = (
    "I am providing THREE images:\n"
    "IMAGE 1 (first): A photo of a real dog — this is the dog you must draw.\n"
    "IMAGE 2 (second): The pixel art profile I already generated for this dog — "
    "you MUST draw the EXACT SAME character with identical colors, markings, and proportions.\n"
    "IMAGE 3 (third): A reference EAT/ATTACK SPRITE SHEET from my game — you MUST match this EXACT "
    "layout, frame size, art style, and dog proportions.\n\n"

    "Generate a HORIZONTAL SPRITE SHEET: exactly 1500x500 pixels total, containing EXACTLY 3 frames "
    "of 500x500 pixels each, placed left to right with NO gaps.\n"
    "Each frame shows the dog in SIDE VIEW facing RIGHT:\n"
    "- Frame 1 (left 500px): Idle pose — standing on all four short legs, neutral expression, "
    "tail slightly raised\n"
    "- Frame 2 (center 500px): Lunge/attack — body lowered and leaning forward, mouth WIDE OPEN "
    "showing pink tongue, ears and tail swept back from momentum\n"
    "- Frame 3 (right 500px): Leap — jumping on hind legs, body angled upward, front paws raised, "
    "mouth open, ears flipped back\n\n"
    "CRITICAL RULES:\n"
    "- The dog must be the SAME SIZE in all 3 frames\n"
    "- The dog must be CENTERED vertically in each 500x500 frame\n"
    "- Match IMAGE 3's layout EXACTLY: same frame spacing, same dog size relative to frame\n"
    "- The dog MUST look identical to IMAGE 2 (same pixel art character)\n\n"
    "{style_core}\n"
    "Output exactly ONE wide image: 1500x500 pixels with all 3 frames side by side."
)

WALK_SPRITE_PROMPT = (
    "I am providing FOUR images:\n"
    "IMAGE 1 (first): A photo of a real dog — this is the dog you must draw.\n"
    "IMAGE 2 (second): The pixel art PROFILE I already generated for this dog — "
    "this defines the character's face, colors, and markings.\n"
    "IMAGE 3 (third): The pixel art RUN SPRITE SHEET I already generated for this SAME dog — "
    "this defines how the character looks in SIDE VIEW. You MUST match this body shape, fur pattern, "
    "and color palette EXACTLY.\n"
    "IMAGE 4 (fourth): A reference WALK SPRITE SHEET from my game — you MUST match this EXACT "
    "layout, frame size, art style, and dog proportions.\n\n"
    "Generate a HORIZONTAL SPRITE SHEET: exactly 2500x500 pixels total, containing EXACTLY 5 walk-cycle "
    "frames (500x500 each), placed left to right with NO gaps.\n"
    "Each frame shows the dog in SIDE VIEW facing RIGHT in a SLOW WALK (not running):\n"
    "- Frame 1: Front-right leg extended forward, back-right extended behind, tail curled up\n"
    "- Frame 2: Weight shifts onto front-right leg (vertical), back-left begins pulling forward\n"
    "- Frame 3: Front-right angling back, front-left passing it, back-left under belly\n"
    "- Frame 4: Front-left lifted high (knee bent), back-left reaching forward, tail curled\n"
    "- Frame 5: Front-left fully extended forward (mirrors frame 1 with opposite legs)\n\n"
    "CRITICAL IDENTITY RULES:\n"
    "- The dog MUST be the EXACT SAME character as in IMAGE 2 and IMAGE 3\n"
    "- Same fur colors, same markings, same ear shape, same body proportions\n"
    "- The dog must be the SAME SIZE in all 5 frames\n"
    "- Only the legs move — body/head stay consistent\n"
    "- Match IMAGE 4's layout EXACTLY: same frame spacing, same dog size relative to frame\n"
    "- This is a GENTLE WALK, not a run — subtle leg movement\n\n"
    "{style_core}\n"
    "Output exactly ONE wide image: 2500x500 pixels with all 5 frames side by side."
)

BOOST_SPRITE_PROMPT = (
    "I am providing MULTIPLE images:\n"
    "IMAGE 1 (first): A photo of a real dog — this is the dog you must draw.\n"
    "IMAGE 2 (second): The pixel art PROFILE I already generated for this dog — "
    "this defines the character's face, colors, and markings.\n"
    "IMAGE 3 (third): The pixel art RUN SPRITE SHEET I already generated for this SAME dog — "
    "this defines how the character looks in SIDE VIEW. You MUST match this body shape, fur pattern, "
    "and color palette EXACTLY.\n"
    "IMAGE 4 (fourth): A reference BOOST sprite from my game showing a dog with wings — "
    "match this EXACT style, wing style, and composition.\n"
    "IMAGE 5-6: Wing reference images — use these exact wing designs.\n\n"
    "Generate a SINGLE 500x500 pixel art sprite of this dog in SIDE VIEW facing RIGHT, "
    "with translucent glowing pixel-art wings naturally emerging from the shoulder/back area.\n"
    "- Wings must look ATTACHED to the body (feather roots blending into fur)\n"
    "- Wings should match the icy-blue translucent style from IMAGE 5-6\n"
    "- The dog's body, colors, and proportions must be IDENTICAL to IMAGE 2 and IMAGE 3\n"
    "- Study IMAGE 4 carefully: match the wing size, position, and how they attach to the dog\n"
    "- This is a boost/power-up state sprite for a retro arcade game\n\n"
    "{style_core}\n"
    "Output exactly ONE square image: 500x500 pixels."
)

FRONT_FLIGHT_PROMPT = (
    "I am providing MULTIPLE reference images from an existing game:\n"
    "IMAGE 1 (first): This dog's pixel art profile/portrait.\n"
    "IMAGE 2 (second): This dog's side-view run sprite sheet.\n"
    "IMAGE 3 (third): This dog's side-view winged boost sprite.\n"
    "IMAGE 4 (fourth): A SHIPPED front-flight sprite from the game — match this EXACT composition, "
    "framing, and pose.\n"
    "IMAGE 5-6: Wing reference images.\n\n"
    "Character: {character_name}, breed: {breed}.\n\n"
    "Generate a SINGLE 500x500 pixel art sprite of this EXACT same dog in FRONT-FACING active flight.\n"
    "- Dog hovering with wings spread, paws slightly lifted, confident airborne pose\n"
    "- Front/straight-on view (facing the viewer)\n"
    "- Preserve the SAME fur colors, markings, body proportions from the references\n"
    "- Silhouette centered and symmetrical for gameplay readability\n"
    "- Match IMAGE 4's scale, framing, and padding around the character EXACTLY\n"
    "- Wings attached naturally to shoulder/back area, matching IMAGE 5-6 wing style\n\n"
    "{style_core}\n"
    "Output exactly ONE square image: 500x500 pixels."
)